In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.DataFrame({'col1': [1,2,3,4,5], 'col2':[23,4,5,6,7], 'col3': "mohana kalaiyarasan 43 years old"})

col1  col2                              col3
0     1    23  mohana kalaiyarasan 43 years old
1     2     4  mohana kalaiyarasan 43 years old
2     3     5  mohana kalaiyarasan 43 years old
3     4     6  mohana kalaiyarasan 43 years old
4     5     7  mohana kalaiyarasan 43 years old

In [4]:
"mohana kalaiyarasan 43 years old".split()

['mohana', 'kalaiyarasan', '43', 'years', 'old']

In [6]:
df = pd.DataFrame({'col1': [1,2,3,4,5], 
              'col2':[23,4,5,6,7], 
              'col3': "mohana kalaiyarasan 43 years old".split()})

In [7]:
df

col1  col2          col3
0     1    23        mohana
1     2     4  kalaiyarasan
2     3     5            43
3     4     6         years
4     5     7           old

In [9]:
#create new column square of all the values in col1
df['col4']=df['col1']**2

In [10]:
df

col1  col2          col3  col4
0     1    23        mohana     1
1     2     4  kalaiyarasan     4
2     3     5            43     9
3     4     6         years    16
4     5     7           old    25

In [20]:
#another way for col4, with apply method()
def test(a):
    return a**2

In [23]:
df['col4_4'] = df['col1'].apply(test)

In [24]:
df

col1  col2          col3  col4 col5  col4_4
0     1    23        mohana     1    m       1
1     2     4  kalaiyarasan     4    k       4
2     3     5            43     9    4       9
3     4     6         years    16    y      16
4     5     7           old    25    o      25

In [11]:
#create a column with the 1st letter of col3
df['col5']=df['col3'].str[0]

In [12]:
df

col1  col2          col3  col4 col5
0     1    23        mohana     1    m
1     2     4  kalaiyarasan     4    k
2     3     5            43     9    4
3     4     6         years    16    y
4     5     7           old    25    o

In [27]:
#col6 is if string of 1st letter is m, print:m others print z
def fun(a):
    if a == 'm':
        return 'm'
    else:
        return 'z'
        
df['col6']=df['col5'].apply(fun)

In [28]:
df

col1  col2          col3  col4 col5  col4_4 col6
0     1    23        mohana     1    m       1    m
1     2     4  kalaiyarasan     4    k       4    z
2     3     5            43     9    4       9    z
3     4     6         years    16    y      16    z
4     5     7           old    25    o      25    z

In [35]:
#same col6 write in lambda function
df['col6_6']=df['col5'].apply(lambda a: 'm' if a =='m' else 'z')

In [36]:
df

col1  col2          col3  col4 col5  col4_4 col6 col6_6
0     1    23        mohana     1    m       1    m      m
1     2     4  kalaiyarasan     4    k       4    z      z
2     3     5            43     9    4       9    z      z
3     4     6         years    16    y      16    z      z
4     5     7           old    25    o      25    z      z

In [37]:
#col7 is len of col3
df['col7'] = df['col3'].apply(len)

In [38]:
df

col1  col2          col3  col4 col5  col4_4 col6 col6_6  col7
0     1    23        mohana     1    m       1    m      m     6
1     2     4  kalaiyarasan     4    k       4    z      z    12
2     3     5            43     9    4       9    z      z     2
3     4     6         years    16    y      16    z      z     5
4     5     7           old    25    o      25    z      z     3

In [40]:
#to have log function
import math

In [41]:
math.log(10)

2.302585092994046

In [42]:
#col8 is log of col2
df['col8']=df['col2'].apply(math.log)

In [43]:
df

col1  col2          col3  col4 col5  col4_4 col6 col6_6  col7      col8
0     1    23        mohana     1    m       1    m      m     6  3.135494
1     2     4  kalaiyarasan     4    k       4    z      z    12  1.386294
2     3     5            43     9    4       9    z      z     2  1.609438
3     4     6         years    16    y      16    z      z     5  1.791759
4     5     7           old    25    o      25    z      z     3  1.945910

In [44]:
l = ['mohan', 2, 4,6]

In [45]:
type(l)

list

In [46]:
np.array(l) #when it listed display the data type of data type, here it is U5

array(['mohan', '2', '4', '6'], dtype='<U5')

In [47]:
type(np.array(l)) #n dimension array

numpy.ndarray

In [56]:
a1 = np.array([3,4,5,6.0]) #because of 1 int is in float 6.0 then all the other int in the list is converted to float type
# type casting into float

In [51]:
a = np.array([[1,2], [3,4]])

In [52]:
a

array([[1, 2],
       [3, 4]])

In [55]:
# get 4 from a
a[1][1]

4

In [57]:
a1

array([3., 4., 5., 6.])

In [58]:
a1[3]

6.0

In [60]:
np.array([1,2,3,5], ndmin=0) #ndmin =0 no changes

array([1, 2, 3, 5])

In [61]:
np.array([1,2,3,5], ndmin=1) #ndmin =1 no changes

array([1, 2, 3, 5])

In [62]:
np.array([1,2,3,5], ndmin=2) #ndmin =2, 2 []bracket

array([[1, 2, 3, 5]])

In [64]:
d = np.array([1,2,3,5], ndmin=4) #ndmin =4, 4 []bracket, array inside array

In [65]:
d

array([[[[1, 2, 3, 5]]]])

In [67]:
#extract 1 in d (4 ndmin) , data parsing
d[0]

array([[[1, 2, 3, 5]]])

In [68]:
d[0][0]

array([[1, 2, 3, 5]])

In [69]:
d[0][0][0]

array([1, 2, 3, 5])

In [70]:
d[0][0][0][0]

1

In [71]:
a #2 dimension array

array([[1, 2],
       [3, 4]])

In [72]:
np.asanyarray([1,2,3,4,6]) #as any array > asanyarray()

array([1, 2, 3, 4, 6])

In [73]:
np.asarray([1,2,3,5,6]) # as array > asarray()

array([1, 2, 3, 5, 6])

In [74]:
np.mat([1,2,3,4,6]) #given 1 dimension but give us 2 dimension 2[]bracket (2d)

matrix([[1, 2, 3, 4, 6]])

In [75]:
a = [1,2,3,5,6,8]
#here a is not an array, it is a list

In [76]:
np.asarray(a)

array([1, 2, 3, 5, 6, 8])

In [77]:
np.mat(a)

matrix([[1, 2, 3, 5, 6, 8]])

In [78]:
np.asanyarray(a) #here asanyarray(), does convert list into an array

array([1, 2, 3, 5, 6, 8])

In [80]:
np.asanyarray(np.mat(a)) #here np.mat(a) is a matrix and when asanyarray(matrix) in this case will not convert if it is already a matrix
#so it give us matrix only, not an array

matrix([[1, 2, 3, 5, 6, 8]])

In [81]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [83]:
np.fromfunction(lambda i, j: i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [90]:
#above gave the result at float, below is in integer
np.fromfunction(lambda i, j: i*j, (4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [94]:
np.fromfunction(lambda i, j, z: i*j*z, (3,3,4), dtype=int)

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6]],

       [[ 0,  0,  0,  0],
        [ 0,  2,  4,  6],
        [ 0,  4,  8, 12]]])

In [95]:
np.fromfunction(lambda i, j, z: i*j*z, (3,3,2), dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [98]:
np.fromfunction(lambda i, j, z: i*j*z, (4,3,4), dtype=int)

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6]],

       [[ 0,  0,  0,  0],
        [ 0,  2,  4,  6],
        [ 0,  4,  8, 12]],

       [[ 0,  0,  0,  0],
        [ 0,  3,  6,  9],
        [ 0,  6, 12, 18]]])

In [99]:
#(4,3,4,3) >> (4 such combination of , 3 matrix of 4x3 matrix )
np.fromfunction(lambda i, j, z, p: i*j*z*p, (4,3,4,3), dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4],
         [ 0,  3,  6]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8],
         [ 0,  6, 12]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8],
         [ 0,  6, 12]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16],
         [ 0, 12, 24]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  3,  6],
        

In [100]:
a=np.fromfunction(lambda i, j, z: i*j*z, (4,3,2), dtype=int)

In [101]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [103]:
#N dimension of array, axis
a.ndim

3

In [104]:
a.size #(4,3,2) > 4x(3x2)

24

In [105]:
#shape of the array
a.shape

(4, 3, 2)

In [106]:
data type of array
a.dtype

dtype('int32')

In [107]:
pd.DataFrame(a)

ValueError: Must pass 2-d input

In [108]:
a=np.fromfunction(lambda i, j: i*j, (4,3), dtype=int)

In [109]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [110]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [111]:
#random values in given shape
np.random.rand(100,4)

array([[0.45996724, 0.98521427, 0.6071214 , 0.7873755 ],
       [0.35651182, 0.83818959, 0.44647865, 0.54528411],
       [0.64468403, 0.91531276, 0.48305538, 0.55092589],
       [0.87810246, 0.39610204, 0.07681147, 0.16931003],
       [0.2037613 , 0.37735536, 0.40556198, 0.69002905],
       [0.38929001, 0.35405038, 0.20929554, 0.11322889],
       [0.2847697 , 0.19087731, 0.91580518, 0.66478596],
       [0.47886944, 0.72604942, 0.77175684, 0.88406428],
       [0.09075466, 0.52793904, 0.3996827 , 0.84604163],
       [0.25778617, 0.91896274, 0.01581497, 0.33443214],
       [0.65677552, 0.61187433, 0.63565366, 0.15796174],
       [0.95112857, 0.54727557, 0.64387966, 0.21361315],
       [0.03338915, 0.26468355, 0.22140148, 0.04313899],
       [0.42264722, 0.00281715, 0.56009806, 0.84826031],
       [0.33697761, 0.44015938, 0.51565303, 0.18600413],
       [0.75614133, 0.58840374, 0.46830039, 0.6043926 ],
       [0.99962956, 0.81002308, 0.08236212, 0.00145969],
       [0.04192397, 0.13350917,

In [113]:
#random 1 integer within a given boundaries
np.random.randint(4,50)

48

In [114]:
#normal distribution
np.random.randn(4,5)

array([[-1.52925314, -0.65893821, -0.61653554,  0.22343667, -1.12055762],
       [ 1.40868156,  1.26120372, -1.12000493,  0.13439232,  1.11562407],
       [ 1.06762052, -0.20681168,  0.32255018,  0.38403272,  0.66288149],
       [ 1.03853601,  0.07936513, -1.25970993,  0.95080757, -1.32084631]])

In [115]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.575786  2.921198 -0.490962 -0.587755  0.628565
1 -1.176616 -0.335477 -0.099809  0.921590 -0.114400
2  0.411266  0.968318 -0.853725 -0.789970  1.374957
3  2.565414 -1.148978  0.854674 -1.638538 -0.000779

In [117]:
#how to convert the dimension of an array
#to convert use, reshape function with given dimension must be given size

a=np.fromfunction(lambda i, j, z: i*j*z, (4,3, 2), dtype=int)

In [118]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [122]:
#in order to convert the array a to dataframe, do reshape and make it as dataframe
pd.DataFrame(a)

ValueError: Must pass 2-d input

In [119]:
#given size is 24, requested reshape is 5*5=25
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [120]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [127]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [121]:
a.reshape(6,3)

ValueError: cannot reshape array of size 24 into shape (6,3)

In [123]:
pd.DataFrame(a.reshape(6,4))

0  1  2  3
0  0  0  0  0
1  0  0  0  0
2  0  1  0  2
3  0  0  0  2
4  0  4  0  0
5  0  3  0  6

In [130]:
#how to convert into 3 dimension
a.reshape(4,3,1,2)

array([[[[0, 0]],

        [[0, 0]],

        [[0, 0]]],


       [[[0, 0]],

        [[0, 1]],

        [[0, 2]]],


       [[[0, 0]],

        [[0, 2]],

        [[0, 4]]],


       [[[0, 0]],

        [[0, 3]],

        [[0, 6]]]])

In [132]:
a.reshape(4,-1) #here size of a array is 24, given row 4 and column -1 represent 6 here

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [135]:
a.reshape(2,-1) #row is 2 and column -1(takes 12), not only -1 will work any negative number will work

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [136]:
a.reshape(2,-15467)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [138]:
a.reshape(2,4,-115)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [139]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [140]:
list(range(4,10, 2))

[4, 6, 8]

In [141]:
list(range(4,10, 0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [144]:
#step size of 0.2 is possible in numpy arange function
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [146]:
a1 = np.arange(4,10.8,0.2)

In [147]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4,
       10.6])

In [148]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [149]:
arr = np.random.rand(4,5)

In [150]:
arr

array([[0.49119294, 0.40233133, 0.44835057, 0.89699622, 0.80552328],
       [0.11500781, 0.29144178, 0.88585511, 0.70202167, 0.2135326 ],
       [0.42255348, 0.74617618, 0.93218133, 0.31993711, 0.01563159],
       [0.54335944, 0.68722047, 0.26737012, 0.79743467, 0.39248606]])

In [151]:
#extract value >0.5
arr[arr>0.5]

array([0.89699622, 0.80552328, 0.88585511, 0.70202167, 0.74617618,
       0.93218133, 0.54335944, 0.68722047, 0.79743467])

In [153]:
#array slicing
arr[1:3,2:4 ]

array([[0.88585511, 0.70202167],
       [0.93218133, 0.31993711]])

In [154]:
arr = np.random.rand(8,5)

In [155]:
arr

array([[0.47174123, 0.21144225, 0.38758912, 0.22822745, 0.5313239 ],
       [0.25862702, 0.34876305, 0.76553085, 0.92529136, 0.49338024],
       [0.11372616, 0.26443696, 0.33410516, 0.88550307, 0.82029541],
       [0.57892796, 0.54944138, 0.70997856, 0.87845144, 0.14839224],
       [0.28045542, 0.84154336, 0.71151342, 0.80547396, 0.07789492],
       [0.6823801 , 0.80436068, 0.17066353, 0.93356752, 0.86562443],
       [0.379752  , 0.61790325, 0.09769017, 0.37002208, 0.06705362],
       [0.76137126, 0.22283031, 0.55462606, 0.51058734, 0.64475004]])

In [156]:
arr[1:,:3]

array([[0.25862702, 0.34876305, 0.76553085],
       [0.11372616, 0.26443696, 0.33410516],
       [0.57892796, 0.54944138, 0.70997856],
       [0.28045542, 0.84154336, 0.71151342],
       [0.6823801 , 0.80436068, 0.17066353],
       [0.379752  , 0.61790325, 0.09769017],
       [0.76137126, 0.22283031, 0.55462606]])

In [160]:
a2=arr[1:8, [0,1,2]]

In [161]:
a2

array([[0.25862702, 0.34876305, 0.76553085],
       [0.11372616, 0.26443696, 0.33410516],
       [0.57892796, 0.54944138, 0.70997856],
       [0.28045542, 0.84154336, 0.71151342],
       [0.6823801 , 0.80436068, 0.17066353],
       [0.379752  , 0.61790325, 0.09769017],
       [0.76137126, 0.22283031, 0.55462606]])

In [162]:
#assign new value
a2[0]

array([0.25862702, 0.34876305, 0.76553085])

In [163]:
a2[0][0] = 100

In [164]:
a2

array([[1.00000000e+02, 3.48763048e-01, 7.65530850e-01],
       [1.13726155e-01, 2.64436956e-01, 3.34105160e-01],
       [5.78927957e-01, 5.49441379e-01, 7.09978556e-01],
       [2.80455416e-01, 8.41543359e-01, 7.11513424e-01],
       [6.82380098e-01, 8.04360678e-01, 1.70663527e-01],
       [3.79752001e-01, 6.17903252e-01, 9.76901745e-02],
       [7.61371261e-01, 2.22830315e-01, 5.54626056e-01]])

In [166]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3], [4,5]])

In [167]:
a

array([[1, 2],
       [3, 4]])

In [168]:
b

array([[2, 3],
       [4, 5]])

In [169]:
a*b #this is not matrix multiplication, element wise / index wise multiplication

array([[ 2,  6],
       [12, 20]])

In [175]:
#matrix multiplication
m = a@b

In [176]:
m

array([[10, 13],
       [22, 29]])

In [178]:
m/0

C:\Users\mral\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf],
       [inf, inf]])

In [179]:
l=[1,2,34,5]

In [180]:
#list to array conversion using asarray function
np.asarray(l)

array([ 1,  2, 34,  5])

In [181]:
#array of 1D of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [183]:
#array of multiple dimension of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [184]:
#array of multiple dimension of zeros
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [185]:
#array of 1D of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [187]:
#array of 2D of ones
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [188]:
5 + np.zeros((3,4)) #vector is an entity which applies to all elements or broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [190]:
#empty array
np.empty((4,5))

array([[0.49119294, 0.40233133, 0.44835057, 0.89699622, 0.80552328],
       [0.11500781, 0.29144178, 0.88585511, 0.70202167, 0.2135326 ],
       [0.42255348, 0.74617618, 0.93218133, 0.31993711, 0.01563159],
       [0.54335944, 0.68722047, 0.26737012, 0.79743467, 0.39248606]])

In [191]:
np.empty((5,4,2))

array([[[0.47174123, 0.21144225],
        [0.38758912, 0.22822745],
        [0.5313239 , 0.25862702],
        [0.34876305, 0.76553085]],

       [[0.92529136, 0.49338024],
        [0.11372616, 0.26443696],
        [0.33410516, 0.88550307],
        [0.82029541, 0.57892796]],

       [[0.54944138, 0.70997856],
        [0.87845144, 0.14839224],
        [0.28045542, 0.84154336],
        [0.71151342, 0.80547396]],

       [[0.07789492, 0.6823801 ],
        [0.80436068, 0.17066353],
        [0.93356752, 0.86562443],
        [0.379752  , 0.61790325]],

       [[0.09769017, 0.37002208],
        [0.06705362, 0.76137126],
        [0.22283031, 0.55462606],
        [0.51058734, 0.64475004]]])

In [192]:
#linearly spaced array between given start and Stop
np.linspace(2,6) #default 50 number

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [194]:
d = np.linspace(2,6,10) 

In [195]:
d

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [197]:
d.reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [202]:
#if lets dont want to consider the upper bound
np.linspace(2,6,10, endpoint=False, retstep= True) #here 6 is not considered

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [203]:
#logarithm Array
np.logspace(2,4, 10,base=10)

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [204]:
np.logspace(2,4, 10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [205]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [213]:
a = np.arange(4,40)

In [214]:
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39])

In [220]:
a = a.reshape(3,6,2)

In [222]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [223]:
a.max()

39

In [224]:
a.max(axis=1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [225]:
a = np.arange(4,40).reshape(6,6)

In [226]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [227]:
a.max()

39

In [228]:
a.max(axis=1) #axis=1 is column but return across row

array([ 9, 15, 21, 27, 33, 39])

In [229]:
a.max(axis=0) # axis =0 is Row but return across column

array([34, 35, 36, 37, 38, 39])

In [230]:
10 + a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [231]:
a/10

array([[0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. , 2.1],
       [2.2, 2.3, 2.4, 2.5, 2.6, 2.7],
       [2.8, 2.9, 3. , 3.1, 3.2, 3.3],
       [3.4, 3.5, 3.6, 3.7, 3.8, 3.9]])

In [232]:
a/0

C:\Users\mral\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [233]:
a**2 #power operation

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [234]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]], dtype=int32)

In [235]:
a*2 #multiply

array([[ 8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66],
       [68, 70, 72, 74, 76, 78]])

In [248]:
b=np.array([2,3,1,2,3,5])

In [249]:
b

array([2, 3, 1, 2, 3, 5])

In [250]:
a + b #broadcasting operation in row wise

array([[ 6,  8,  7,  9, 11, 14],
       [12, 14, 13, 15, 17, 20],
       [18, 20, 19, 21, 23, 26],
       [24, 26, 25, 27, 29, 32],
       [30, 32, 31, 33, 35, 38],
       [36, 38, 37, 39, 41, 44]])

In [275]:
a.ndim

2

In [251]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [280]:
b=np.array([2,3,1,2,3,5])

In [281]:
b.ndim

1

In [282]:
b.shape

(6,)

In [283]:
b = b.T #Transpose

In [284]:
a + b #with transpose operation will not perform the column wise addition with 1d

array([[ 6,  8,  7,  9, 11, 14],
       [12, 14, 13, 15, 17, 20],
       [18, 20, 19, 21, 23, 26],
       [24, 26, 25, 27, 29, 32],
       [30, 32, 31, 33, 35, 38],
       [36, 38, 37, 39, 41, 44]])

In [285]:
b.shape # 1d array and 1 dimension

(6,)

In [287]:
b = b.reshape(1,6) #convert to 2D array

In [288]:
b.shape

(1, 6)

In [289]:
b=b.reshape(1,-1) #same as 2D array, -1 is other dimension

In [290]:
b.shape

(1, 6)

In [291]:
b

array([[2, 3, 1, 2, 3, 5]])

In [292]:
b.ndim

2

In [293]:
b=b.T

In [294]:
b

array([[2],
       [3],
       [1],
       [2],
       [3],
       [5]])

In [295]:
b.ndim

2

In [296]:
a+b

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [39, 40, 41, 42, 43, 44]])

In [297]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [300]:
#square root
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [301]:
#exponential
np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [302]:
np.log(a)

array([[1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154,
        2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
        3.04452244],
       [3.09104245, 3.13549422, 3.17805383, 3.21887582, 3.25809654,
        3.29583687],
       [3.33220451, 3.36729583, 3.40119738, 3.4339872 , 3.4657359 ,
        3.49650756],
       [3.52636052, 3.55534806, 3.58351894, 3.61091791, 3.63758616,
        3.66356165]])

In [303]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804, 0.90308999,
        0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
        1.32221929],
       [1.34242268, 1.36172784, 1.38021124, 1.39794001, 1.41497335,
        1.43136376],
       [1.44715803, 1.462398  , 1.47712125, 1.49136169, 1.50514998,
        1.51851394],
       [1.53147892, 1.54406804, 1.5563025 , 1.56820172, 1.5797836 ,
        1.59106461]])

In [304]:
x = np.array([1,2,3])

In [305]:
y = x #assign x to y, same memory location -- SHALLOW COPY

In [306]:
y

array([1, 2, 3])

In [307]:
z = np.copy(x) #new memory location created as z -- DEEP COPY

In [308]:
z

array([1, 2, 3])

In [309]:
x[0] = 100 #new value to x[0]

In [310]:
x

array([100,   2,   3])

In [311]:
y #it is reflected in the same memory location

array([100,   2,   3])

In [312]:
z

array([1, 2, 3])

In [313]:
id(z) #identity of an object

2753901508208

In [314]:
id(x) #memory index of x 

2753901396576

In [315]:
id(y) #memory index of y is same as x (same identity)

2753901396576

In [317]:
id(x[0]) #here x[0]

2753906919824

In [318]:
id(y[0]) #here y[0] is not using same identity

2753906919120

In [319]:
su = np.array([567,345])

In [320]:
df = su

In [321]:
id(su)

2753899362384

In [322]:
id(df) #same identity of su

2753899362384

In [323]:
id(su[0])

2753906920464

In [324]:
id(df[0])

2753916446096

In [325]:
id(su[1])

2753916447120

In [326]:
id(df[1])

2753906919152

In [327]:
id(su[0]) == id(df[0]) #how can it be True?

True

In [328]:
id(su[0]) == id(df[1]) #how can it be True?

True

In [329]:
xt=np.array([34,67,89])

In [330]:
id(xt[0])==id(su[0])

True

In [ ]:
What is the actual meaning of id()?
What is wrong in the above statement?
Why is in below case is False?

In [331]:
c = "mohan"

In [332]:
id(c)==id(su[0])

False