Pycharm:
from flask import Flask, request, jsonify

@app.route('/xyz', methods=['GET', 'POST']) #below this sentence as decorator and reach out this functions
def test(a,b):
    print(a+b)
    return a+b

test(3,4)

Need the address of this function (root) to reach out for the function
- create root in first place
    similar like @mohana, like @app.route('xyz')
    
Both are send the data to different system:
method GET - related to accessibility, sending the data but dataset is exposed, ex: google search
method POST - related to Security, sending the data where data is not exposed (ex: email password). password is not a part of the body(Hidden)

In [1]:
import numpy as np
import pandas as pd

In [7]:
np.random.randint(1, 50, size=7)

array([ 6, 37, 41, 22, 27, 12, 43])

In [8]:
np.random.randint(1, 50, size=7)

array([40, 35, 46, 16, 20, 39, 49])

In [16]:
np.random.randint(1, 50, size=7)

array([19,  6, 23, 30,  3, 18, 44])

In [10]:
np.random.randint(1, 50, size=7)

array([39, 23,  3, 34, 36, 45, 18])

In [11]:
np.random.randint(1, 50, size=7)

array([12, 32, 20, 38, 33, 30, 16])

In [12]:
np.random.randint(1, 50, size=7)

array([13, 32, 28,  2, 14, 29, 47])

In [13]:
np.random.randint(1, 50, size=7)

array([23, 35, 35, 44, 31, 32, 14])

In [14]:
np.random.randint(1, 50, size=7)

array([44, 29,  3, 35, 48, 14,  3])

In [15]:
np.random.randint(1, 50, size=7)

array([ 4, 40, 21, 28, 37, 12, 22])

In [17]:
from flask import Flask, request, jsonify

# object of this flask, all the functions of the name is imported in flask
app = Flask(__name__)


# below this sentence as decorator / annotation and reach out this functions
@app.route('/xyz', methods=['GET', 'POST'])
def test():
    if request.method == 'POST':
        a = request.json['num1']
        b = request.json['num2']
        result = a + b
        return jsonify(str(result))

@app.route('/abc/moha', methods=['POST'])
def test1():
    if request.method == 'POST':
        a = request.json['num3']
        b = request.json['num4']
        result = a + b
        return jsonify(str(result))

@app.route('/abc/moha/kala', methods=['POST'])
def test2():
    if request.method == 'POST':
        a = request.json['num4']
        b = request.json['num5']
        result = a + b
        return jsonify(str(result))

@app.route('/abc/xyz', methods=['POST'])
def test3():
    if request.method == 'POST':
        a = request.json['moha']
        b = request.json['kalai']
        result = a + b
        return jsonify(str(result))

if __name__ == '__main__':
    app.run()


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


In [1]:
1 . write a function to fetch data from sql table via api 
2 . write a function to fetch a data from mongodb table

SyntaxError: invalid syntax (<ipython-input-1-4ddf2690bb4a>, line 1)