# What is NumPy?
<!-- NumPy is a Python library used for working with arrays.
NumPy stands for Numerical Python.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. -->

import numpy 
arr = numpy.array([1,2,3,4,5])
print(arr)

In [1]:
import numpy 
arr = numpy.array([1,2,3,4,5]) 
print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np
arr = np.array((1,2,3,4,5)) #np.array() function, inside the function might be list or tuples
print(arr)
print(np.__version__)
print(type(arr))

[1 2 3 4 5]
1.18.1
<class 'numpy.ndarray'>


In [8]:
# 1D, 2D and 3D array
import numpy as np
#arr = np.array([1, 2, 3, 4, 5]) # 1D array
arr = np.array(([1, 2, 3], [4, 5, 6])) # 2D array
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
import statistics
print(statistics.median([5, 15, 10, 20, 13, 17, 12, 14, 18, 16]))


14.5
